"""
Django settings for socialnetwork2024 project.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

MEDIA_ROOT = '%s/social/static/' % BASE_DIR

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-p4d6g84q0-wkck)-mj+^asr&ur^d%&k+dmebf1spn7iwf+7^je'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['192.168.1.16']

#KIEU MINH TUAN ALLOWED_HOSTS
# ALLOWED_HOSTS = ['192.168.110.94']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'social.apps.SocialConfig',
    'ckeditor',
    'ckeditor_uploader',
    'rest_framework',
    'drf_yasg',
    'oauth2_provider',
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'oauth2_provider.contrib.rest_framework.OAuth2Authentication',
    )
}

AUTH_USER_MODEL = 'social.User'

CKEDITOR_UPLOAD_PATH = "images/ckeditor/"

import pymysql

pymysql.install_as_MySQLdb()

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'socialnetwork2024.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'socialnetwork2024.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'socialdb',
        'USER': 'root',
        'PASSWORD': 'Admin@123',
        'HOST': ''  # mặc định localhost
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

import cloudinary

cloudinary.config(
    cloud_name="djlyy5s5e",
    api_key="248579782829654",
    api_secret="sxkpzv4-ePJKtM6PFD6ZUi6FHxE",  # Click 'View API Keys' above to copy your API secret
    secure=True
)

OAUTH2_PROVIDER = { 'OAUTH2_BACKEND_CLASS': 'oauth2_provider.oauth2_backends.JSONOAuthLibCore' }
#Client của Hoàng
# CLIENT_ID = "sk88zYNryhW9rJCe0IWtvc9gTfc6HIrIPU3rZwwo"
# CLIENT_SECRET = "9ow1onA8S3Xr6kvrFTabEveDFD1RCNZc7aOSy5VOWaF07bP8PouHxkTBVFJ8HM0y47GeaRbU74WUfjDVXafrPLWyvmpY2NufmOU9AC9qaEdang51qWSfrLvLPqjRz3FL"


#Client local của Hoàng
# CLIENT_ID = "cM4zjyT3xpp6RncyTVVszv6M10MDPMma2ROJ38m9"
# CLIENT_SECRET = "FyqfMZ3JHxGDEjInYjyVAjzD0DNV5Uo2cFZP3HqHbpVZsCCJxHjs0RdKyCpwDk95KVCUZTGlkY3JPKndJVBzCgSJWiwE701PKrsM5SH3PQAOp0RcszVdWAulmypSosPR"


#KIEU MINH TUAN
#CLIENT_ID = "hRWkWbAYvbkKO4R8G6LHeRWcf17Pobk4icaCC3xW"
#CLIENT_SECRET = "bje4vzlkczK2Y72iTjGw28bCAicB0quEwTQxyt0TvaNn7c6oidXUo5JZqbQHvCjnetjOZmDauFheQz7hTOlwhAygbZUdVFWx4s4KCxlwosd5aIzb43ClQUREJDGZlkWe"
#KIEU MINH TUAN VISUAL CODE
#CLIENT_ID = "75Ql2NZmMboqNzLkqGnhjhgVAmXEtDkKlm7BmlV4"
#CLIENT_SECRET = "vzZXtT7cCC32pGw0djXXKWqt4OWCxVEU7mdcvDnBD5YaRJrvQICNS4kdsAolQ1F7IXqxletmmYeh9b4xgEcywY2irRl0lhqAi3HfvThXhcp2M3OZ80sn7g89i6YtmvOt"