# Generated by Django 5.1.4 on 2025-01-24 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0008_alter_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Quản trị viên'), ('lecturer', 'Giảng viên'), ('alumni', 'Cựu sinh viên')], default='alumni', max_length=20),
        ),
    ]
