# Generated by Django 5.1.4 on 2025-02-02 14:46

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0010_post_user_alter_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pic_cover',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
    ]
