# Generated by Django 5.1.2 on 2024-10-24 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('created_day', models.DateTimeField(auto_now_add=True)),
                ('updated_day', models.DateTimeField(auto_now=True)),
                ('subject', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='courses/%Y/%m/')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
