import { StyleSheet } from "react-native";

export default StyleSheet.create({
    container: { flex: 1, backgroundColor: '#f8f8f8' },
    header: { flexDirection: 'row', alignItems: 'center', padding: 10, backgroundColor: '#fff', elevation: 2 },
    headerTitle: { fontSize: 20, fontWeight: 'bold', flex: 1 },
    searchBar: { flex: 2, marginHorizontal: 10, padding: 5, borderWidth: 1, borderColor: '#ccc', borderRadius: 5 },
    menuButton: { padding: 5 },
    menuText: { fontSize: 20 },
    content: { padding: 10 },
    inputSection: { flexDirection: 'row', alignItems: 'center', marginBottom: 20, padding: 10, backgroundColor: '#fff', borderRadius: 5, elevation: 1 },
    avatar: { width: 40, height: 40, backgroundColor: '#ccc', borderRadius: 20, marginRight: 10 },
    input: { flex: 1, fontSize: 16 },
    post: { backgroundColor: '#fff', padding: 10, borderRadius: 5, marginBottom: 20, elevation: 1 },
    postHeader: { flexDirection: 'row', alignItems: 'center', marginBottom: 10 },
    postAvatar: { width: 40, height: 40, backgroundColor: '#ccc', borderRadius: 20, marginRight: 10 },
    postAuthor: { fontSize: 16, fontWeight: 'bold' },
    postDate: { fontSize: 12, color: '#555' },
    exchangeButton: { marginLeft: 'auto', fontSize: 14, color: '#007BFF' },
    postContent: { fontSize: 16, marginBottom: 5 },
    postTag: { fontSize: 14, color: '#007BFF', marginBottom: 10 },
    postFooter: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 10 },
    postStats: { fontSize: 12, color: '#555' },
    postComments: { fontSize: 12, color: '#555' },
    actions: { flexDirection: 'row', justifyContent: 'space-around' },
    actionButton: { fontSize: 14, color: '#007BFF' },
    footer: { flexDirection: 'row', justifyContent: 'space-around', padding: 10, backgroundColor: '#fff', elevation: 2 },
    footerButton: { fontSize: 16, color: '#007BFF' },
  });